SELECT
A.REST_ID, A.REST_NAME, A.FOOD_TYPE, A.FAVORITES, A.ADDRESS, ROUND(avg(B.REVIEW_SCORE),2) AS SCORE
FROM REST_INFO A join REST_REVIEW B on A.REST_ID = B.REST_ID
WHERE A.ADDRESS LIKE '서울%'
GROUP BY
  A.REST_ID, A.REST_NAME, A.FOOD_TYPE, A.FAVORITES, A.ADDRESS
ORDER BY SCORE DESC, A.FAVORITES DESC;