SELECT 
    a.ID, C.FISH_NAME, a.LENGTH
FROM FISH_INFO a
join( SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LENGTH FROM FISH_INFO GROUP BY FISH_TYPE) b
ON a.LENGTH = b.MAX_LENGTH AND a.FISH_TYPE =b.FISH_TYPE
JOIN FISH_NAME_INFO c
on a.FISH_TYPE = c.FISH_TYPE
ORDER BY a.ID asc;